/**
 * @author Midware
 * @Website www.midware.net
 * @developer Roy Cordero
 * @contact contact@midware.net
 */
define(["require", "exports", "../Views/VendorPortalView", "../../../Global/Constants", "../../../Global/Functions"], function (require, exports, vendorPortalView, constants, functions) {
    Object.defineProperty(exports, "__esModule", { value: true });
    // Get the view of the Reset Password Page
    function getResetPasswordView(pUserID, pVendorData, pVendorApprovalRequestData, pPageID) {
        var titleData = vendorPortalView.getTitleData(pPageID);
        return "\n        <head>\n            <title>Vendor Portal</title>\n            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.js\"></script>\n            <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css\">\n\n            <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.GLOBAL.CSS) + "\">\n            <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.VENDOR_PORTAL.CSS) + "\">\n            <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.SIDEBAR.CSS) + "\">\n            <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.HOME.CSS) + "\">\n            <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" />\n            <script type='text/javascript' src=\"" + functions.getFileUrl(constants.FILES.GLOBAL.JS) + "\"></script>\n            <script type='text/javascript' src=\"" + functions.getFileUrl(constants.FILES.VENDOR_PORTAL.JS) + "\"></script>\n            <script type='text/javascript' src=\"" + functions.getFileUrl(constants.FILES.SIDEBAR.JS) + "\"></script>\n            <script type='text/javascript' src=\"" + functions.getFileUrl(constants.FILES.HOME.JS) + "\"></script>\n        </head>\n        <div aria-live=\"polite\"  role=\"alert\" aria-atomic=\"true\" >\n            <div role=\"alert\" class=\"toast\" style=\"position: absolute; top: 5px; right: 5px; min-width: 200px;\" data-delay=\"10000\">\n                <div class=\"toast-header\" style=\"background-color: #FAD2D2;\">\n                <strong class=\"mr-auto\">Error</strong>\n                </div>\n                <div class=\"toast-body\" id=\"error-message\">\n                </div>\n            </div>\n        </div>\n        <div class=\"wrapper\">\n            <div class=\"sidebar-view\">\n                " + vendorPortalView.getSidebarView(pVendorApprovalRequestData) + "\n            </div>\n            <div class=\"body\">\n                <div class=\"header\">\n                    <div class=\"main-title\">\n                        <a href=\"" + vendorPortalView.getHomePageLink() + "\" class=\"vendor-portal-title\"><h3>Vendor Portal</h3></a>\n                        " + (pVendorData ? "<span class=\"vendor-header\">" + pVendorData[constants.VENDOR.FIELDS.ALTNAME] + "</span>" : "") + "\n                    </div>\n                    " + (pVendorData && pVendorData[constants.VENDOR.FIELDS.LOGO] && pVendorData[constants.VENDOR.FIELDS.LOGO][0] && pVendorData[constants.VENDOR.FIELDS.LOGO][0].text ?
            "<div>\n                        <img class=\"vendor-logo\" src=\"" + pVendorData[constants.VENDOR.FIELDS.LOGO][0].text + "\">\n                    </div>" : "") + "\n                    <div>\n                        <img class=\"logo-tov\" src=\"https://s3-us-west-1.amazonaws.com/tov-stage/wp-content/uploads/2019/01/Tov-Logo-Update.jpg\">\n                    </div>\n                </div>\n                <div class=\"vendor-portal\">\n                    <div class=\"category-title-wrapper\">\n                        <div class=\"circle category-title pink\">\n                            " + titleData.icon + "\n                        </div>\n                        <span class=\"category-title\">" + titleData.title + "</span>\n                    </div>\n                    <form action=\"" + functions.getCurrentSuiteletURL(true) + "&userID=" + pUserID + "&page=" + constants.PAGES_IDS.RESET_PASSWORD + "\" method=\"post\">\n                        <p>Please type in your new password.</p>\n                        <label for=\"password\">Password</label>\n                        <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"*******\" required>\n                        <input class=\"button\" type=\"submit\" value=\"Set password\">\n                    </form>\n                </div>\n            </div>\n        </div>\n    ";
    }
    exports.getResetPasswordView = getResetPasswordView;
    // Get the view of the Reset Password Page
    function getResetPasswordSuccessView(pVendorData, pVendorApprovalRequestData, pPageID) {
        var titleData = vendorPortalView.getTitleData(pPageID);
        return "\n        <head>\n            <title>Vendor Portal</title>\n            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.js\"></script>\n            <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css\">\n\n            <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.GLOBAL.CSS) + "\">\n            <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.VENDOR_PORTAL.CSS) + "\">\n            <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.SIDEBAR.CSS) + "\">\n            <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.HOME.CSS) + "\">\n            <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" />\n            <script type='text/javascript' src=\"" + functions.getFileUrl(constants.FILES.GLOBAL.JS) + "\"></script>\n            <script type='text/javascript' src=\"" + functions.getFileUrl(constants.FILES.VENDOR_PORTAL.JS) + "\"></script>\n            <script type='text/javascript' src=\"" + functions.getFileUrl(constants.FILES.SIDEBAR.JS) + "\"></script>\n            <script type='text/javascript' src=\"" + functions.getFileUrl(constants.FILES.HOME.JS) + "\"></script>\n        </head>\n        <div aria-live=\"polite\"  role=\"alert\" aria-atomic=\"true\" >\n            <div role=\"alert\" class=\"toast\" style=\"position: absolute; top: 5px; right: 5px; min-width: 200px;\" data-delay=\"10000\">\n                <div class=\"toast-header\" style=\"background-color: #FAD2D2;\">\n                <strong class=\"mr-auto\">Error</strong>\n                </div>\n                <div class=\"toast-body\" id=\"error-message\">\n                </div>\n            </div>\n        </div>\n        <div class=\"wrapper\">\n            <div class=\"sidebar-view\">\n                " + vendorPortalView.getSidebarView(pVendorApprovalRequestData) + "\n            </div>\n            <div class=\"body\">\n                <div class=\"header\">\n                    <div class=\"main-title\">\n                        <a href=\"" + vendorPortalView.getHomePageLink() + "\" class=\"vendor-portal-title\"><h3>Vendor Portal</h3></a>\n                        " + (pVendorData ? "<span class=\"vendor-header\">" + pVendorData[constants.VENDOR.FIELDS.ALTNAME] + "</span>" : "") + "\n                    </div>\n                    " + (pVendorData && pVendorData[constants.VENDOR.FIELDS.LOGO] && pVendorData[constants.VENDOR.FIELDS.LOGO][0] && pVendorData[constants.VENDOR.FIELDS.LOGO][0].text ?
            "<div>\n                        <img class=\"vendor-logo\" src=\"" + pVendorData[constants.VENDOR.FIELDS.LOGO][0].text + "\">\n                    </div>" : "") + "\n                    <div>\n                        <img class=\"logo-tov\" src=\"https://s3-us-west-1.amazonaws.com/tov-stage/wp-content/uploads/2019/01/Tov-Logo-Update.jpg\">\n                    </div>\n                </div>\n                <div class=\"vendor-portal\">\n                    <div class=\"category-title-wrapper\">\n                        <div class=\"circle category-title pink\">\n                            " + titleData.icon + "\n                        </div>\n                        <span class=\"category-title\">" + titleData.title + "</span>\n                    </div>\n                    <p>Your password has been set successfully.</p>\n               </div>\n            </div>\n        </div>\n    ";
    }
    exports.getResetPasswordSuccessView = getResetPasswordSuccessView;
});
