/**
 * @author Midware
 * @developer Bailin Huang
 * @contact contact@midware.net
 */
define(["require", "exports", "../../../Global/Constants", "../../../Global/Functions", "./css/style"], function (require, exports, constants, functions, styles) {
    Object.defineProperty(exports, "__esModule", { value: true });
    function getResetPasswordFormView(pParams) {
        var userID = pParams.userID, token = pParams.token;
        //Add invisible label with a redirect url and add the params for it
        var html = "\n    <head>\n        <title>Vendor Portal</title>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.js\"></script>\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css\">\n\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.GLOBAL.CSS) + "\">\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" />\n    </head>\n    <body>\n        <div class=\"main-container wrapper fadeInDown row\">\n            <div id=\"formContent\" class=\"formContent col\">\n                <div class=\"logo-container\">\n                    <img class=\"logo-tov\" src=\"https://s3-us-west-1.amazonaws.com/tov-stage/wp-content/uploads/2019/01/Tov-Logo-Update.jpg\">\n                </div>\n                <form action=\"" + functions.getCurrentSuiteletURL(true) + "&resetpassword=true&userID=" + userID + "&token=" + token + "\" method=\"post\">\n                    <h1>Vendor Portal Login</h1>\n                    <h2>Set Password</h2>\n                    <p>Please type in your new password.</p>\n                    <label for=\"password\">Password</label>\n                    <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"*******\" required>\n                    <input class=\"button\" type=\"submit\" value=\"Set password\">\n                </form>\n            </div>\n        </div>\n        " + styles.MAIN_STYLE + "\n    </body>";
        return html;
    }
    exports.getResetPasswordFormView = getResetPasswordFormView;
    function getResetPasswordLinkErrorView() {
        var html = "\n    <head>\n        <title>Vendor Portal</title>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.js\"></script>\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css\">\n\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.GLOBAL.CSS) + "\">\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" />\n    </head>\n    <body>\n        <div class=\"main-container wrapper fadeInDown row\">\n            <div id=\"formContent\" class=\"formContent col\">\n                <div class=\"logo-container\">\n                    <img class=\"logo-tov\" src=\"https://s3-us-west-1.amazonaws.com/tov-stage/wp-content/uploads/2019/01/Tov-Logo-Update.jpg\">\n                </div>\n                <h1>Vendor Portal</h1>\n                <h2>Set Password</h2>\n                <p>Your link is invalid, please request a new link.</p>\n                <div id=\"formFooter\">\n                    <a class=\"underlineHover\" href=\"" + functions.getCurrentSuiteletURL(true) + "\">Go back to login</a>\n                </div>\n            </div>\n        </div>\n        " + styles.MAIN_STYLE + "\n    </body>";
        return html;
    }
    exports.getResetPasswordLinkErrorView = getResetPasswordLinkErrorView;
    function getResetPasswordSuccessView() {
        var html = "\n    <head>\n        <title>Vendor Portal</title>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.js\"></script>\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css\">\n\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.GLOBAL.CSS) + "\">\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" />\n    </head>\n    <body>\n        <div class=\"main-container wrapper fadeInDown row\">\n            <div id=\"formContent\" class=\"formContent col\">\n                <div class=\"logo-container\">\n                    <img class=\"logo-tov\" src=\"https://s3-us-west-1.amazonaws.com/tov-stage/wp-content/uploads/2019/01/Tov-Logo-Update.jpg\">\n                </div>\n                <h1>Vendor Portal</h1>\n                <h2>Set Password</h2>\n                <p>Your password has been set successfully.</p>\n                <div id=\"formFooter\">\n                    <a class=\"underlineHover\" href=\"" + functions.getCurrentSuiteletURL(true) + "\">Go back to login</a>\n                </div>\n            </div>\n        </div>\n        " + styles.MAIN_STYLE + "\n    </body>";
        return html;
    }
    exports.getResetPasswordSuccessView = getResetPasswordSuccessView;
});
