define(["require", "exports", "../../../Global/Constants", "../../../Global/Functions", "./css/style"], function (require, exports, constants, functions, styles) {
    Object.defineProperty(exports, "__esModule", { value: true });
    function getForgotPasswordFormView(error) {
        var emailErrorMessage = "";
        if (error == constants.LOGIN_STATE.ACCOUNT_NOT_FOUND) {
            emailErrorMessage = "<span aria-live=\"polite\" class=\"error\">This email is not registered or is not a vendor.</span>";
        }
        var html = "\n    <head>\n        <title>Vendor Portal</title>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.js\"></script>\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css\">\n\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.GLOBAL.CSS) + "\">\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" />\n    </head>\n    <body>\n        <div class=\"main-container row\">\n            <div id=\"formContent\" class=\"formContent col\">\n                <div class=\"logo-container\">\n                    <img class=\"logo-tov\" src=\"https://s3-us-west-1.amazonaws.com/tov-stage/wp-content/uploads/2019/01/Tov-Logo-Update.jpg\">\n                </div>\n                <form action=\"" + functions.getCurrentSuiteletURL(true) + "&forgotPassword=true\" method=\"post\">\n                    <h1>Vendor Portal</h1>\n                    <h2>Lost your password?</h2>\n                    <p>Please enter your email address. You will receive a link to create a new password via email.</p>\n                    <label for=\"email\">Email</label>\n                    <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"example@email.com\" required>\n                    " + emailErrorMessage + "\n                    <input class=\"button\" type=\"submit\" value=\"Send reset email\">\n                </form>\n                <div id=\"formFooter\">\n                    <a class=\"underlineHover\" href=\"" + functions.getCurrentSuiteletURL(true) + "\">Go back to login</a>\n                </div>\n            </div>\n        </div>\n        " + styles.MAIN_STYLE + "\n    </body>";
        return html;
    }
    exports.getForgotPasswordFormView = getForgotPasswordFormView;
    function getResetPasswordEmailSentView() {
        var html = "\n    <head>\n        <title>Vendor Portal</title>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.js\"></script>\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css\">\n\n        <link rel=\"stylesheet\" type=\"text/css\" href=\"" + functions.getFileUrl(constants.FILES.GLOBAL.CSS) + "\">\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" />\n    </head>\n    <body>\n        <div class=\"main-container row\">\n            <div id=\"formContent\" class=\"formContent col\">\n                <div class=\"logo-container\">\n                    <img class=\"logo-tov\" src=\"https://s3-us-west-1.amazonaws.com/tov-stage/wp-content/uploads/2019/01/Tov-Logo-Update.jpg\">\n                </div>\n                <h1>Vendor Portal</h1>\n                <h2>Reset Password Email Sent</h2>\n                <p>An email with a link to create a new password has been sent. Please check your email inbox and spam.</p>\n                <div id=\"formFooter\">\n                    <a class=\"underlineHover\" href=\"" + functions.getCurrentSuiteletURL(true) + "\">Go back to login</a>\n                </div>\n            </div>\n        </div>\n        " + styles.MAIN_STYLE + "\n    </body>";
        return html;
    }
    exports.getResetPasswordEmailSentView = getResetPasswordEmailSentView;
});
